export * from './auth-signin-passport-router'
export * from './auth-public-process-router'
export * from './auth-private-process-router'
export * from './path-base-domain-router'
export * from './domain-private-router'
export * from './global-private-router'
