export const USER_NOT_FOUND = 'user-not-found'
export const PASSWORD_NOT_MATCHED = 'password-not-matched'
export const USER_NOT_ACTIVATED = 'user-not-activated'
export const USER_LOCKED = 'user-locked'
export const USER_DELETED = 'user-deleted'
export const NO_AVAILABLE_DOMAIN = 'no-available-domain'
export const UNAVAILABLE_DOMAIN = 'unavailable-domain'
